import colors from '../../constants/colors';

const AdminStyle = {
  page: {
    width: '100%',
    background: colors.gradients.main,
    display: 'flex',
    justifyContent: 'center',
    padding: '52px 18px 74px',
    minHeight: 'calc(100vh - 72px)',
  },
  container: {
    width: '100%',
    maxWidth: 1180,
  },

  hero: {
    textAlign: 'center',
    marginBottom: 18,
  },
  badge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 10,
    padding: '10px 16px',
    borderRadius: 999,
    background: 'rgba(255,255,255,0.92)',
    boxShadow: '0 14px 30px rgba(0,0,0,0.14)',
    marginBottom: 18,
  },
  badgeIcon: { fontSize: 16 },
  badgeText: {
    fontSize: 13,
    fontWeight: 900,
    color: colors.primary[600],
  },
  badgeDot: { fontSize: 16 },
  title: {
    margin: 0,
    fontSize: 56,
    fontWeight: 950,
    letterSpacing: -0.9,
    color: colors.neutral.white,
    textShadow: '0 14px 40px rgba(0,0,0,0.18)',
  },
  subtitle: {
    margin: '12px auto 0',
    maxWidth: 760,
    fontSize: 16,
    fontWeight: 750,
    color: 'rgba(255,255,255,0.92)',
    lineHeight: 1.6,
    textShadow: '0 10px 26px rgba(0,0,0,0.14)',
  },

  card: {
    marginTop: 16,
    background: colors.neutral.white,
    borderRadius: 22,
    padding: 18,
    boxShadow: '0 22px 60px rgba(0,0,0,0.18)',
  },
  simpleTitle: { margin: 0, fontWeight: 950, color: colors.neutral[900] },
  simpleText: { marginTop: 10, fontWeight: 850, color: colors.neutral[700] },
  row: {
    display: 'flex',
    gap: 10,
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  rowMt14: {
    marginTop: 14,
    display: 'flex',
    gap: 10,
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  tabRow: {
    marginTop: 14,
    display: 'flex',
    gap: 10,
    flexWrap: 'wrap',
    alignItems: 'center',
  },
  tabBtn: {
    height: 44,
    padding: '0 14px',
    borderRadius: 999,
    border: `1px solid ${colors.neutral[200]}`,
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: 950,
    boxShadow: '0 10px 24px rgba(0,0,0,0.08)',
    background: colors.neutral.white,
    color: colors.neutral[800],
  },
  tabBtnActive: {
    background: colors.gradients.main,
    color: colors.neutral.white,
    border: 'none',
  },
  grid: {
    marginTop: 16,
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))',
    gap: 14,
  },
  section: {
    borderRadius: 22,
    border: `1px solid ${colors.neutral[200]}`,
    padding: 16,
    background: colors.neutral.white,
    boxShadow: '0 18px 50px rgba(0,0,0,0.10)',
  },
  sectionTitle: {
    margin: 0,
    fontSize: 16,
    fontWeight: 950,
    color: colors.neutral[900],
    letterSpacing: -0.3,
  },
  sectionSub: {
    marginTop: 6,
    fontSize: 13,
    fontWeight: 850,
    color: colors.neutral[650],
    lineHeight: 1.5,
  },

  field: {
    marginTop: 12,
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
  },
  label: {
    fontSize: 12,
    fontWeight: 950,
    color: colors.neutral[800],
  },
  input: {
    height: 44,
    padding: '0 12px',
    borderRadius: 14,
    border: `1px solid ${colors.neutral[200]}`,
    outline: 'none',
    fontSize: 14,
    fontWeight: 850,
    color: colors.neutral[900],
    background: colors.neutral.white,
    boxShadow: '0 10px 24px rgba(0,0,0,0.08)',
  },
  select: {
    height: 44,
    padding: '0 12px',
    borderRadius: 14,
    border: `1px solid ${colors.neutral[200]}`,
    outline: 'none',
    fontSize: 14,
    fontWeight: 900,
    color: colors.neutral[900],
    background: colors.neutral.white,
    boxShadow: '0 10px 24px rgba(0,0,0,0.08)',
  },
  textarea: {
    minHeight: 90,
    padding: 12,
    borderRadius: 14,
    border: `1px solid ${colors.neutral[200]}`,
    outline: 'none',
    fontSize: 14,
    fontWeight: 850,
    color: colors.neutral[900],
    background: colors.neutral.white,
    boxShadow: '0 10px 24px rgba(0,0,0,0.08)',
    resize: 'vertical',
  },

  btn: {
    height: 46,
    padding: '0 16px',
    borderRadius: 16,
    border: `1px solid ${colors.neutral[200]}`,
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 950,
    boxShadow: '0 12px 26px rgba(0,0,0,0.10)',
    background: colors.neutral.white,
    color: colors.neutral[900],
  },
  btnMt14: {
    marginTop: 14,
    height: 46,
    padding: '0 16px',
    borderRadius: 16,
    border: `1px solid ${colors.neutral[200]}`,
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 950,
    boxShadow: '0 12px 26px rgba(0,0,0,0.10)',
    background: colors.neutral.white,
    color: colors.neutral[900],
  },
  btnPrimary: {
    background: colors.gradients.main,
    color: colors.neutral.white,
    border: 'none',
  },
  btnPrimaryFull: {
    height: 46,
    padding: '0 16px',
    borderRadius: 16,
    border: 'none',
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 950,
    boxShadow: '0 12px 26px rgba(0,0,0,0.10)',
    background: colors.gradients.main,
    color: colors.neutral.white,
  },

  error: {
    marginTop: 12,
    padding: '10px 12px',
    borderRadius: 16,
    border: `1px solid ${colors.secondary[100]}`,
    background: colors.secondary[50],
    color: colors.secondary[700],
    fontSize: 13,
    fontWeight: 850,
  },
  success: {
    marginTop: 12,
    padding: '10px 12px',
    borderRadius: 16,
    border: `1px solid ${colors.primary[200]}`,
    background: 'rgba(139,44,255,0.08)',
    color: colors.primary[800],
    fontSize: 13,
    fontWeight: 850,
  },

  list: {
    marginTop: 12,
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
  },
  listItem: {
    padding: 12,
    borderRadius: 18,
    border: `1px solid ${colors.neutral[200]}`,
    background: colors.neutral[50],
  },
  listItemTitle: {
    fontSize: 13,
    fontWeight: 950,
    color: colors.neutral[900],
    lineHeight: 1.3,
  },
  listItemMeta: {
    marginTop: 8,
    display: 'flex',
    gap: 8,
    flexWrap: 'wrap',
    alignItems: 'center',
  },
  smallHelp: {
    marginTop: 10,
    fontSize: 12,
    fontWeight: 850,
    color: colors.neutral[650],
    lineHeight: 1.5,
  },
  pill: {
    padding: '7px 10px',
    borderRadius: 999,
    background: colors.neutral.white,
    border: `1px solid ${colors.neutral[200]}`,
    fontSize: 12,
    fontWeight: 950,
    color: colors.neutral[800],
    whiteSpace: 'nowrap',
  },
};

export default AdminStyle;
