import colors from '../../constants/colors';

const AuthModalStyle: any = {
  overlay: {
    position: 'fixed',
    inset: 0,
    zIndex: 2000,
    background: 'rgba(17, 24, 39, 0.55)',
    backdropFilter: 'blur(10px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 'clamp(10px, 3.5vw, 22px)',
  },

  card: {
    width: '100%',
    maxWidth: 980,
    borderRadius: 26,
    maxHeight: 'calc(100vh - 44px)',
    overflowX: 'hidden',
    overflowY: 'auto',
    background: colors.neutral.white,
    boxShadow: '0 30px 90px rgba(0,0,0,0.35)',
    display: 'flex',
    flexWrap: 'wrap',
    position: 'relative',
  },

  closeBtn: {
    position: 'absolute',
    top: 14,
    right: 14,
    width: 42,
    height: 42,
    borderRadius: 14,
    border: '1px solid rgba(255,255,255,0.25)',
    background: 'rgba(255,255,255,0.18)',
    color: colors.neutral.white,
    cursor: 'pointer',
    fontSize: 16,
    fontWeight: 900,
    backdropFilter: 'blur(10px)',
    zIndex: 2,
  },

  left: {
    flex: '1 1 360px',
    minHeight: 420,
    padding: 'clamp(22px, 5vw, 40px) clamp(18px, 5vw, 38px)',
    background: colors.gradients.main,
    color: colors.neutral.white,
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    gap: 18,
  },

  leftBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 10,
    padding: '10px 14px',
    borderRadius: 999,
    background: 'rgba(255,255,255,0.18)',
    boxShadow: 'inset 0 1px 0 rgba(255,255,255,0.22)',
    backdropFilter: 'blur(10px)',
    marginBottom: 18,
    width: 'fit-content',
  },
  leftBadgeIcon: { fontSize: 16 },
  leftBadgeText: { fontSize: 13, fontWeight: 900 },

  leftTitle: {
    margin: 0,
    fontSize: 'clamp(26px, 4.6vw, 34px)',
    fontWeight: 950,
    letterSpacing: -0.7,
    textShadow: '0 10px 30px rgba(0,0,0,0.20)',
  },
  brand: {
    background: `linear-gradient(90deg, ${colors.accent.yellow} 0%, rgba(255,255,255,0.95) 60%)`,
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
  },
  leftSubtitle: {
    marginTop: 12,
    marginBottom: 0,
    fontSize: 15,
    fontWeight: 700,
    color: 'rgba(255,255,255,0.92)',
    lineHeight: 1.55,
    maxWidth: 360,
  },

  perks: {
    marginTop: 22,
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
  },
  perkRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    padding: '10px 12px',
    borderRadius: 16,
    background: 'rgba(255,255,255,0.14)',
    boxShadow: 'inset 0 1px 0 rgba(255,255,255,0.18)',
    backdropFilter: 'blur(10px)',
    width: 'fit-content',
  },
  perkIcon: { fontSize: 18 },
  perkText: { fontSize: 14, fontWeight: 850 },

  leftFooter: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 10,
    padding: '10px 14px',
    borderRadius: 999,
    background: 'rgba(255,255,255,0.14)',
    fontSize: 13,
    fontWeight: 800,
    width: 'fit-content',
  },
  leftFooterDot: { opacity: 0.9 },

  sparkle: {
    position: 'absolute',
    fontSize: 22,
    userSelect: 'none',
    opacity: 0.95,
  },
  sparkleTopRight: {
    position: 'absolute',
    fontSize: 22,
    userSelect: 'none',
    opacity: 0.95,
    top: 18,
    right: 20,
  },
  sparkleBottomLeft: {
    position: 'absolute',
    fontSize: 22,
    userSelect: 'none',
    opacity: 0.95,
    bottom: 22,
    left: 22,
  },

  right: {
    flex: '1 1 360px',
    padding: 'clamp(20px, 5vw, 38px) clamp(18px, 5vw, 36px)',
    background: colors.neutral.white,
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
  },

  header: {
    paddingRight: 40,
  },
  title: {
    margin: 0,
    fontSize: 28,
    fontWeight: 950,
    color: colors.neutral[900],
    letterSpacing: -0.6,
  },
  subtitle: {
    margin: '8px 0 0',
    fontSize: 14,
    fontWeight: 750,
    color: colors.neutral[600],
  },

  tabRow: {
    display: 'flex',
    gap: 10,
    padding: 6,
    borderRadius: 999,
    background: colors.neutral[100],
    width: 'fit-content',
  },
  tabBtn: {
    border: 'none',
    cursor: 'pointer',
    padding: '10px 14px',
    borderRadius: 999,
    background: 'transparent',
    fontSize: 13,
    fontWeight: 900,
    color: colors.neutral[700],
  },
  tabBtnActive: {
    background: colors.neutral.white,
    color: colors.primary[600],
    boxShadow: '0 10px 20px rgba(0,0,0,0.08)',
  },
  tabBtnState: (active: boolean) => ({
    border: 'none',
    cursor: 'pointer',
    padding: '10px 14px',
    borderRadius: 999,
    background: active ? colors.neutral.white : 'transparent',
    fontSize: 13,
    fontWeight: 900,
    color: active ? colors.primary[600] : colors.neutral[700],
    ...(active ? { boxShadow: '0 10px 20px rgba(0,0,0,0.08)' } : null),
  }),

  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: 14,
    marginTop: 6,
  },

  dividerRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    marginTop: 2,
    marginBottom: 2,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    background: colors.neutral[200],
  },
  dividerText: {
    fontSize: 12,
    fontWeight: 850,
    color: colors.neutral[500],
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },

  socialWrap: {
    display: 'flex',
    justifyContent: 'center',
    width: '100%',
  },
  socialDisabled: {
    opacity: 0.6,
    pointerEvents: 'none',
  },
  field: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  label: {
    fontSize: 13,
    fontWeight: 900,
    color: colors.neutral[800],
  },
  input: {
    height: 46,
    padding: '0 14px',
    borderRadius: 14,
    border: `1px solid ${colors.neutral[200]}`,
    background: colors.neutral.white,
    fontSize: 14,
    fontWeight: 650,
    color: colors.neutral[900],
    outline: 'none',
    boxShadow: '0 10px 24px rgba(0,0,0,0.06)',
  },
  inputError: {
    border: `1px solid ${colors.accent.red}`,
    boxShadow: `0 10px 24px rgba(244, 63, 94, 0.14)`,
  },
  errorText: {
    fontSize: 12,
    fontWeight: 800,
    color: colors.accent.red,
    marginTop: 4,
  },

  errorBanner: {
    margin: '12px 0 0',
    padding: '10px 12px',
    borderRadius: 14,
    background: colors.secondary[50],
    border: `1px solid ${colors.secondary[100]}`,
    color: colors.secondary[700],
    fontSize: 13,
    fontWeight: 850,
  },

  submitBtn: {
    marginTop: 4,
    height: 48,
    borderRadius: 16,
    border: 'none',
    cursor: 'pointer',
    color: colors.neutral.white,
    fontSize: 15,
    fontWeight: 950,
    boxShadow: '0 18px 34px rgba(139,44,255,0.28)',
  },
  submitBtnMain: {
    marginTop: 4,
    height: 48,
    borderRadius: 16,
    border: 'none',
    cursor: 'pointer',
    color: colors.neutral.white,
    fontSize: 15,
    fontWeight: 950,
    boxShadow: '0 18px 34px rgba(139,44,255,0.28)',
    background: colors.gradients.main,
  },

  altRow: {
    marginTop: 2,
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  altText: {
    fontSize: 13,
    fontWeight: 750,
    color: colors.neutral[600],
  },
  altLink: {
    border: 'none',
    background: 'transparent',
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: 950,
    color: colors.primary[600],
    padding: 0,
  },

  resendRow: {
    marginTop: 4,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  resendBtn: {
    border: 'none',
    background: 'transparent',
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: 950,
    color: colors.primary[600],
    padding: 0,
    textAlign: 'left',
  },
  resendHint: {
    fontSize: 12,
    fontWeight: 800,
    color: colors.neutral[600],
    lineHeight: 1.35,
  },
  resendMsg: {
    margin: 0,
    fontSize: 12,
    fontWeight: 850,
    color: colors.neutral[700],
  },
};

export default AuthModalStyle;

