import colors from '../../constants/colors';

const CreateQuizPageStyle = {
  page: {
    width: '100%',
    background: colors.gradients.main,
    display: 'flex',
    justifyContent: 'center',
    padding: '52px 18px 74px',
  },

  container: {
    width: '100%',
    maxWidth: 1180,
  },

  hero: {
    textAlign: 'center',
    marginBottom: 28,
  },
  heroBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 10,
    padding: '10px 16px',
    borderRadius: 999,
    background: 'rgba(255,255,255,0.92)',
    boxShadow: '0 14px 30px rgba(0,0,0,0.14)',
    marginBottom: 18,
  },
  heroBadgeIcon: { fontSize: 16 },
  heroBadgeText: {
    fontSize: 13,
    fontWeight: 900,
    color: colors.primary[600],
  },
  heroBadgeDot: { fontSize: 16 },

  heroTitle: {
    margin: 0,
    fontSize: 60,
    fontWeight: 950,
    letterSpacing: -0.9,
    color: colors.neutral.white,
    textShadow: '0 14px 40px rgba(0,0,0,0.18)',
  },
  heroTitleAccent: {
    background: `linear-gradient(90deg, ${colors.accent.yellow} 0%, rgba(255,255,255,0.95) 60%)`,
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
  },
  heroSubtitle: {
    margin: '12px auto 0',
    maxWidth: 720,
    fontSize: 16,
    fontWeight: 750,
    color: 'rgba(255,255,255,0.92)',
    lineHeight: 1.6,
    textShadow: '0 10px 26px rgba(0,0,0,0.14)',
  },

  grid: {
    marginTop: 18,
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: 18,
  },

  panel: {
    background: colors.neutral.white,
    borderRadius: 22,
    padding: 22,
    boxShadow: '0 22px 60px rgba(0,0,0,0.18)',
  },
  panelWide: {
    background: colors.neutral.white,
    borderRadius: 22,
    padding: 22,
    boxShadow: '0 22px 60px rgba(0,0,0,0.18)',
  },
  panelWideHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  panelTitle: {
    margin: 0,
    fontSize: 20,
    fontWeight: 950,
    color: colors.neutral[900],
    letterSpacing: -0.4,
  },
  panelHint: {
    margin: '10px 0 14px',
    fontSize: 13,
    fontWeight: 750,
    color: colors.neutral[600],
  },

  form: {
    marginTop: 14,
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
  },
  field: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  fieldFlex1: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    flex: 1,
  },
  smallField: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    width: 140,
  },
  label: {
    fontSize: 13,
    fontWeight: 900,
    color: colors.neutral[800],
  },
  input: {
    height: 46,
    padding: '0 14px',
    borderRadius: 14,
    border: `1px solid ${colors.neutral[200]}`,
    background: colors.neutral.white,
    fontSize: 14,
    fontWeight: 700,
    color: colors.neutral[900],
    outline: 'none',
    boxShadow: '0 10px 24px rgba(0,0,0,0.06)',
  },
  textarea: {
    minHeight: 92,
    padding: '12px 14px',
    borderRadius: 14,
    border: `1px solid ${colors.neutral[200]}`,
    background: colors.neutral.white,
    fontSize: 14,
    fontWeight: 650,
    color: colors.neutral[900],
    outline: 'none',
    boxShadow: '0 10px 24px rgba(0,0,0,0.06)',
    resize: 'vertical',
  },

  primaryBtn: {
    height: 48,
    borderRadius: 16,
    border: 'none',
    cursor: 'pointer',
    color: colors.neutral.white,
    fontSize: 15,
    fontWeight: 950,
    boxShadow: '0 18px 34px rgba(139,44,255,0.28)',
  },
  primaryBtnMain: {
    height: 48,
    borderRadius: 16,
    border: 'none',
    cursor: 'pointer',
    color: colors.neutral.white,
    fontSize: 15,
    fontWeight: 950,
    boxShadow: '0 18px 34px rgba(139,44,255,0.28)',
    background: colors.gradients.main,
  },
  primaryBtnMainEnd: {
    height: 48,
    borderRadius: 16,
    border: 'none',
    cursor: 'pointer',
    color: colors.neutral.white,
    fontSize: 15,
    fontWeight: 950,
    boxShadow: '0 18px 34px rgba(139,44,255,0.28)',
    background: colors.gradients.main,
    alignSelf: 'flex-end',
  },
  secondaryBtn: {
    height: 46,
    padding: '0 16px',
    borderRadius: 16,
    border: `1px solid ${colors.neutral[200]}`,
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 900,
    color: colors.neutral[900],
    boxShadow: '0 12px 26px rgba(0,0,0,0.08)',
  },
  secondaryBtnWhite: {
    height: 46,
    padding: '0 16px',
    borderRadius: 16,
    border: `1px solid ${colors.neutral[200]}`,
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 900,
    color: colors.neutral[900],
    boxShadow: '0 12px 26px rgba(0,0,0,0.08)',
    background: colors.neutral.white,
  },

  inlineRow: {
    display: 'flex',
    gap: 10,
    alignItems: 'center',
  },

  myQuizList: {
    marginTop: 14,
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
    maxHeight: 360,
    overflow: 'auto',
    paddingRight: 6,
  },
  myQuizRow: {
    display: 'flex',
    gap: 10,
    alignItems: 'stretch',
  },
  myQuizOpenBtn: {
    flex: '1 1 auto',
  },
  myQuizDeleteBtn: {
    flex: '0 0 auto',
    width: 44,
    minWidth: 44,
    borderRadius: 18,
    border: `1px solid ${colors.neutral[200]}`,
    background: colors.neutral.white,
    cursor: 'pointer',
    boxShadow: '0 14px 30px rgba(0,0,0,0.10)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: colors.secondary[700],
    fontSize: 16,
    fontWeight: 950,
  },
  myQuizItem: {
    width: '100%',
    textAlign: 'left',
    padding: 14,
    borderRadius: 18,
    border: `1px solid ${colors.neutral[200]}`,
    background: colors.neutral.white,
    cursor: 'pointer',
    boxShadow: '0 14px 30px rgba(0,0,0,0.10)',
  },
  myQuizItemOpen: {
    width: '100%',
    textAlign: 'left',
    padding: 14,
    borderRadius: 18,
    border: `1px solid ${colors.neutral[200]}`,
    background: colors.neutral.white,
    cursor: 'pointer',
    boxShadow: '0 14px 30px rgba(0,0,0,0.10)',
    flex: '1 1 auto',
  },
  myQuizTitleRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  myQuizTitle: {
    fontSize: 14,
    fontWeight: 950,
    color: colors.neutral[900],
    letterSpacing: -0.2,
  },
  myQuizStatus: {
    padding: '6px 10px',
    borderRadius: 999,
    background: colors.neutral[100],
    border: `1px solid ${colors.neutral[200]}`,
    color: colors.neutral[800],
    fontSize: 12,
    fontWeight: 950,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    whiteSpace: 'nowrap',
  },
  myQuizMeta: {
    marginTop: 10,
    display: 'flex',
    gap: 8,
    flexWrap: 'wrap',
    alignItems: 'center',
  },
  myQuizMetaItem: {
    fontSize: 12,
    fontWeight: 850,
    color: colors.neutral[700],
    background: colors.neutral[100],
    border: `1px solid ${colors.neutral[200]}`,
    padding: '6px 10px',
    borderRadius: 999,
  },

  quizHeader: {
    marginTop: 16,
    paddingTop: 16,
    borderTop: `1px solid ${colors.neutral[200]}`,
    display: 'flex',
    justifyContent: 'space-between',
    gap: 12,
    alignItems: 'flex-start',
    flexWrap: 'wrap',
  },
  quizTitleRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    flexWrap: 'wrap',
  },
  quizTitle: {
    margin: 0,
    fontSize: 18,
    fontWeight: 950,
    color: colors.neutral[900],
    letterSpacing: -0.3,
  },
  quizDesc: {
    margin: '8px 0 0',
    fontSize: 13,
    fontWeight: 700,
    color: colors.neutral[600],
    lineHeight: 1.5,
    maxWidth: 460,
  },
  metaRow: {
    marginTop: 10,
    display: 'flex',
    gap: 10,
    flexWrap: 'wrap',
    alignItems: 'center',
  },
  metaItem: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    padding: '8px 10px',
    borderRadius: 999,
    background: colors.neutral[100],
    border: `1px solid ${colors.neutral[200]}`,
    fontSize: 12,
    fontWeight: 900,
    color: colors.neutral[800],
  },
  metaIcon: { fontSize: 14 },
  code: {
    fontSize: 12,
    fontWeight: 950,
    color: colors.neutral[900],
    background: 'transparent',
  },

  actions: {
    display: 'flex',
    gap: 10,
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  actionBtn: {
    height: 46,
    padding: '0 16px',
    borderRadius: 16,
    border: `1px solid ${colors.neutral[200]}`,
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 950,
    boxShadow: '0 12px 26px rgba(0,0,0,0.08)',
  },
  actionBtnWhite: {
    height: 46,
    padding: '0 16px',
    borderRadius: 16,
    border: `1px solid ${colors.neutral[200]}`,
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 950,
    boxShadow: '0 12px 26px rgba(0,0,0,0.08)',
    background: colors.neutral.white,
  },
  actionBtnDelete: {
    height: 46,
    padding: '0 16px',
    borderRadius: 16,
    border: `1px solid ${colors.secondary[100]}`,
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 950,
    boxShadow: '0 12px 26px rgba(0,0,0,0.08)',
    background: colors.neutral.white,
    color: colors.secondary[700],
  },
  actionBtnPublish: {
    height: 46,
    padding: '0 16px',
    borderRadius: 16,
    border: `1px solid ${colors.neutral[200]}`,
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 950,
    boxShadow: '0 12px 26px rgba(0,0,0,0.08)',
    background: colors.gradients.main,
    color: colors.neutral.white,
  },
  pill: {
    padding: '6px 10px',
    borderRadius: 999,
    background: colors.neutral[100],
    border: `1px solid ${colors.neutral[200]}`,
    color: colors.neutral[800],
    fontSize: 12,
    fontWeight: 950,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  pillOk: {
    background: colors.secondary[50],
    border: `1px solid ${colors.secondary[100]}`,
    color: colors.secondary[700],
  },
  pillState: (ok) => ({
    padding: '6px 10px',
    borderRadius: 999,
    fontSize: 12,
    fontWeight: 950,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    ...(ok
      ? {
          background: colors.secondary[50],
          border: `1px solid ${colors.secondary[100]}`,
          color: colors.secondary[700],
        }
      : {
          background: colors.neutral[100],
          border: `1px solid ${colors.neutral[200]}`,
          color: colors.neutral[800],
        }),
  }),

  builder: {
    marginTop: 18,
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
  },

  questionForm: {
    marginTop: 14,
    display: 'flex',
    gap: 12,
    alignItems: 'flex-end',
    flexWrap: 'wrap',
  },

  questionsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: 16,
  },

  questionCard: {
    background: colors.neutral.white,
    borderRadius: 22,
    padding: 18,
    boxShadow: '0 18px 50px rgba(0,0,0,0.16)',
    border: `1px solid ${colors.neutral[100]}`,
  },
  questionTop: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  questionNumber: {
    width: 44,
    height: 44,
    borderRadius: 16,
    background: colors.primary[50],
    color: colors.primary[700],
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 14,
    fontWeight: 950,
  },
  questionMeta: {
    display: 'flex',
    gap: 8,
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  questionMetaItem: {
    fontSize: 12,
    fontWeight: 900,
    color: colors.neutral[700],
    background: colors.neutral[100],
    border: `1px solid ${colors.neutral[200]}`,
    padding: '6px 10px',
    borderRadius: 999,
  },
  questionText: {
    marginTop: 12,
    fontSize: 14,
    fontWeight: 850,
    color: colors.neutral[900],
    lineHeight: 1.45,
  },

  options: {
    marginTop: 12,
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  optionRow: {
    display: 'flex',
    gap: 10,
    alignItems: 'center',
    padding: '10px 12px',
    borderRadius: 16,
    background: colors.neutral[50],
    border: `1px solid ${colors.neutral[200]}`,
  },
  correctRadioLabel: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    marginRight: 8,
  },
  optionLabel: {
    width: 20,
    textAlign: 'right',
    fontSize: 12,
    fontWeight: 950,
    color: colors.neutral[600],
  },
  optionText: {
    flex: 1,
    fontSize: 13,
    fontWeight: 850,
    color: colors.neutral[900],
  },
  correctPill: {
    padding: '6px 10px',
    borderRadius: 999,
    background: colors.accent.green,
    color: colors.neutral.white,
    fontSize: 12,
    fontWeight: 950,
  },
  emptyOptions: {
    padding: '10px 12px',
    borderRadius: 16,
    background: colors.secondary[50],
    border: `1px solid ${colors.secondary[100]}`,
    color: colors.secondary[700],
    fontSize: 12,
    fontWeight: 900,
  },

  addOptionRow: {
    marginTop: 12,
    display: 'flex',
    gap: 10,
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  checkbox: {
    display: 'inline-flex',
    gap: 8,
    alignItems: 'center',
    fontSize: 13,
    fontWeight: 900,
    color: colors.neutral[800],
    background: colors.neutral[100],
    border: `1px solid ${colors.neutral[200]}`,
    padding: '10px 12px',
    borderRadius: 16,
  },

  accessWrap: {
    marginTop: 18,
    paddingTop: 16,
    borderTop: `1px solid ${colors.neutral[200]}`,
  },
  accessHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    flexWrap: 'wrap',
  },
  accessTitle: {
    margin: 0,
    fontSize: 16,
    fontWeight: 950,
    color: colors.neutral[900],
    letterSpacing: -0.3,
  },
  accessList: {
    marginTop: 12,
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
  },
  accessItem: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    padding: '12px 12px',
    borderRadius: 18,
    background: colors.neutral[50],
    border: `1px solid ${colors.neutral[200]}`,
  },
  accessUser: {
    fontSize: 13,
    fontWeight: 950,
    color: colors.neutral[900],
  },
  accessRemove: {
    height: 40,
    padding: '0 14px',
    borderRadius: 16,
    border: `1px solid ${colors.neutral[200]}`,
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: 950,
    color: colors.secondary[700],
    background: colors.neutral.white,
    boxShadow: '0 10px 22px rgba(0,0,0,0.06)',
  },

  lockCard: {
    maxWidth: 560,
    margin: '18px auto 0',
    borderRadius: 22,
    padding: 26,
    background: colors.neutral.white,
    boxShadow: '0 22px 60px rgba(0,0,0,0.18)',
    textAlign: 'center',
  },
  lockTitle: {
    margin: 0,
    fontSize: 24,
    fontWeight: 950,
    color: colors.neutral[900],
    letterSpacing: -0.5,
  },
  lockText: {
    margin: '10px auto 18px',
    maxWidth: 460,
    fontSize: 14,
    fontWeight: 750,
    color: colors.neutral[600],
    lineHeight: 1.55,
  },

  errorCard: {
    background: colors.neutral.white,
    borderRadius: 22,
    padding: 18,
    boxShadow: '0 18px 50px rgba(0,0,0,0.16)',
    border: `1px solid ${colors.secondary[100]}`,
  },
  errorTitle: {
    fontSize: 14,
    fontWeight: 950,
    color: colors.secondary[700],
  },
  errorText: {
    marginTop: 6,
    fontSize: 13,
    fontWeight: 750,
    color: colors.neutral[700],
    lineHeight: 1.5,
  },
};

export default CreateQuizPageStyle;
