import colors from '../../constants/colors';

const DiscoverQuizzesStyle = {
  page: {
    width: '100%',
    background: colors.gradients.main,
    display: 'flex',
    justifyContent: 'center',
    padding: '52px 18px 74px',
  },
  container: {
    width: '100%',
    maxWidth: 1180,
  },

  hero: {
    textAlign: 'center',
    marginBottom: 18,
  },
  badge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 10,
    padding: '10px 16px',
    borderRadius: 999,
    background: 'rgba(255,255,255,0.92)',
    boxShadow: '0 14px 30px rgba(0,0,0,0.14)',
    marginBottom: 18,
  },
  badgeIcon: { fontSize: 16 },
  badgeText: {
    fontSize: 13,
    fontWeight: 900,
    color: colors.primary[600],
  },
  badgeDot: { fontSize: 16 },

  title: {
    margin: 0,
    fontSize: 56,
    fontWeight: 950,
    letterSpacing: -0.9,
    color: colors.neutral.white,
    textShadow: '0 14px 40px rgba(0,0,0,0.18)',
  },
  titleAccent: {
    background: `linear-gradient(90deg, ${colors.accent.yellow} 0%, rgba(255,255,255,0.95) 60%)`,
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
  },
  subtitle: {
    margin: '12px auto 0',
    maxWidth: 720,
    fontSize: 16,
    fontWeight: 750,
    color: 'rgba(255,255,255,0.92)',
    lineHeight: 1.6,
    textShadow: '0 10px 26px rgba(0,0,0,0.14)',
  },

  note: {
    margin: '12px auto 0',
    maxWidth: 760,
    display: 'inline-flex',
    alignItems: 'center',
    gap: 10,
    padding: '10px 14px',
    borderRadius: 999,
    background: 'rgba(255,255,255,0.16)',
    color: colors.neutral.white,
    fontSize: 13,
    fontWeight: 850,
    boxShadow: 'inset 0 1px 0 rgba(255,255,255,0.22)',
    backdropFilter: 'blur(10px)',
  },
  noteIcon: { fontSize: 15 },

  searchCard: {
    marginTop: 16,
    background: colors.neutral.white,
    borderRadius: 22,
    padding: 18,
    boxShadow: '0 22px 60px rgba(0,0,0,0.18)',
  },
  searchRow: {
    display: 'flex',
    gap: 10,
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  input: {
    height: 46,
    padding: '0 14px',
    borderRadius: 14,
    border: `1px solid ${colors.neutral[200]}`,
    background: colors.neutral.white,
    fontSize: 14,
    fontWeight: 700,
    color: colors.neutral[900],
    outline: 'none',
    boxShadow: '0 10px 24px rgba(0,0,0,0.06)',
    flex: '1 1 320px',
  },
  btn: {
    height: 46,
    padding: '0 16px',
    borderRadius: 16,
    border: `1px solid ${colors.neutral[200]}`,
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 950,
    boxShadow: '0 12px 26px rgba(0,0,0,0.10)',
  },
  error: {
    marginTop: 12,
    padding: '10px 12px',
    borderRadius: 16,
    border: `1px solid ${colors.secondary[100]}`,
    background: colors.secondary[50],
    color: colors.secondary[700],
    fontSize: 13,
    fontWeight: 850,
  },

  grid: {
    marginTop: 18,
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: 16,
  },

  quizCard: {
    width: '100%',
    textAlign: 'left',
    padding: 18,
    borderRadius: 22,
    border: `1px solid rgba(255,255,255,0.24)`,
    background: 'rgba(255,255,255,0.90)',
    cursor: 'pointer',
    boxShadow: '0 18px 50px rgba(0,0,0,0.16)',
  },
  cardTop: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  quizTitle: {
    fontSize: 18,
    fontWeight: 950,
    color: colors.neutral[900],
    letterSpacing: -0.4,
    lineHeight: 1.2,
  },
  pills: {
    display: 'flex',
    gap: 8,
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
  },
  pill: {
    padding: '7px 10px',
    borderRadius: 999,
    background: colors.neutral[100],
    border: `1px solid ${colors.neutral[200]}`,
    color: colors.neutral[800],
    fontSize: 12,
    fontWeight: 950,
    whiteSpace: 'nowrap',
  },
  meta: {
    marginTop: 12,
    display: 'flex',
    gap: 10,
    flexWrap: 'wrap',
    alignItems: 'center',
  },
  metaItem: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    padding: '7px 10px',
    borderRadius: 999,
    background: colors.neutral[50],
    border: `1px solid ${colors.neutral[200]}`,
    fontSize: 12,
    fontWeight: 850,
    color: colors.neutral[800],
  },
  metaIcon: { fontSize: 14 },

  desc: {
    marginTop: 12,
    fontSize: 13,
    fontWeight: 750,
    color: colors.neutral[700],
    lineHeight: 1.5,
  },
  openHint: {
    marginTop: 14,
    fontSize: 13,
    fontWeight: 950,
    color: colors.primary[600],
  },

  empty: {
    marginTop: 22,
    textAlign: 'center',
    color: colors.neutral.white,
    padding: '26px 18px',
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: 950,
    textShadow: '0 10px 26px rgba(0,0,0,0.16)',
  },
  emptyText: {
    marginTop: 8,
    fontSize: 14,
    fontWeight: 750,
    color: 'rgba(255,255,255,0.92)',
  },
};

export default DiscoverQuizzesStyle;

