import colors from '../../constants/colors';

const DuelPlayStyle = {
  page: {
    width: '100%',
    background: colors.gradients.main,
    display: 'flex',
    justifyContent: 'center',
    padding: '36px 18px 74px',
  },
  container: {
    width: '100%',
    maxWidth: 980,
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
  },

  topRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    flexWrap: 'wrap',
  },
  pills: {
    display: 'flex',
    gap: 8,
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  pill: {
    padding: '8px 12px',
    borderRadius: 999,
    background: 'rgba(255,255,255,0.18)',
    border: '1px solid rgba(255,255,255,0.22)',
    color: colors.neutral.white,
    fontSize: 12,
    fontWeight: 950,
    boxShadow: 'inset 0 1px 0 rgba(255,255,255,0.18)',
    backdropFilter: 'blur(10px)',
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
  },

  card: {
    background: colors.neutral.white,
    borderRadius: 26,
    padding: 20,
    boxShadow: '0 22px 60px rgba(0,0,0,0.18)',
  },

  qTitle: {
    margin: 0,
    fontSize: 16,
    fontWeight: 950,
    color: colors.neutral[900],
    letterSpacing: -0.3,
  },
  qText: {
    marginTop: 10,
    fontSize: 20,
    fontWeight: 950,
    color: colors.neutral[900],
    letterSpacing: -0.4,
    lineHeight: 1.35,
  },

  options: {
    marginTop: 16,
    display: 'grid',
    gridTemplateColumns: 'repeat(1, minmax(0, 1fr))',
    gap: 12,
  },
  optionBtnState: (selected, disabled) => ({
    width: '100%',
    textAlign: 'left',
    padding: 14,
    borderRadius: 20,
    border: selected ? `1px solid ${colors.primary[200]}` : `1px solid ${colors.neutral[200]}`,
    background: selected ? colors.primary[50] : colors.neutral.white,
    cursor: disabled ? 'not-allowed' : 'pointer',
    boxShadow: selected ? '0 0 0 2px rgba(139,44,255,0.18), 0 14px 30px rgba(0,0,0,0.10)' : '0 14px 30px rgba(0,0,0,0.10)',
    display: 'flex',
    gap: 12,
    alignItems: 'center',
    opacity: disabled ? 0.6 : 1,
  }),
  optionLabel: {
    width: 36,
    height: 36,
    borderRadius: 14,
    background: colors.neutral[100],
    border: `1px solid ${colors.neutral[200]}`,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 12,
    fontWeight: 950,
    color: colors.neutral[800],
    flex: '0 0 auto',
  },
  optionText: {
    fontSize: 14,
    fontWeight: 850,
    color: colors.neutral[900],
    lineHeight: 1.35,
  },

  toast: {
    marginTop: 14,
    padding: '10px 12px',
    borderRadius: 16,
    fontSize: 13,
    fontWeight: 950,
    background: colors.neutral[100],
    border: `1px solid ${colors.neutral[200]}`,
    color: colors.neutral[800],
    display: 'inline-flex',
    alignItems: 'center',
    gap: 10,
  },
  toastOk: {
    background: 'rgba(34,197,94,0.12)',
    border: '1px solid rgba(34,197,94,0.35)',
    color: colors.accent.green,
  },
  toastBad: {
    background: 'rgba(239,68,68,0.12)',
    border: '1px solid rgba(239,68,68,0.35)',
    color: colors.accent.red,
  },
  toastState: (isMine) => ({
    marginTop: 14,
    padding: '10px 12px',
    borderRadius: 16,
    fontSize: 13,
    fontWeight: 950,
    background: isMine ? 'rgba(34,197,94,0.12)' : 'rgba(239,68,68,0.12)',
    border: isMine ? '1px solid rgba(34,197,94,0.35)' : '1px solid rgba(239,68,68,0.35)',
    color: isMine ? colors.accent.green : colors.accent.red,
    display: 'inline-flex',
    alignItems: 'center',
    gap: 10,
  }),

  btnWhite: {
    height: 46,
    padding: '0 16px',
    borderRadius: 16,
    border: `1px solid ${colors.neutral[200]}`,
    background: colors.neutral.white,
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 950,
    color: colors.neutral[900],
    boxShadow: '0 12px 26px rgba(0,0,0,0.10)',
  },
  errorCard: {
    background: colors.neutral.white,
    borderRadius: 22,
    padding: 16,
    border: `1px solid ${colors.secondary[100]}`,
    color: colors.secondary[700],
    fontSize: 13,
    fontWeight: 850,
    boxShadow: '0 18px 50px rgba(0,0,0,0.16)',
  },
};

export default DuelPlayStyle;
