import colors from '../../constants/colors';

const FriendsStyle = {
  page: {
    width: '100%',
    background: colors.gradients.main,
    display: 'flex',
    justifyContent: 'center',
    padding: '52px 18px 74px',
  },
  container: {
    width: '100%',
    maxWidth: 1180,
  },

  hero: {
    textAlign: 'center',
    marginBottom: 18,
  },
  badge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 10,
    padding: '10px 16px',
    borderRadius: 999,
    background: 'rgba(255,255,255,0.92)',
    boxShadow: '0 14px 30px rgba(0,0,0,0.14)',
    marginBottom: 18,
  },
  badgeIcon: { fontSize: 16 },
  badgeText: {
    fontSize: 13,
    fontWeight: 900,
    color: colors.primary[600],
  },
  badgeDot: { fontSize: 16 },

  title: {
    margin: 0,
    fontSize: 56,
    fontWeight: 950,
    letterSpacing: -0.9,
    color: colors.neutral.white,
    textShadow: '0 14px 40px rgba(0,0,0,0.18)',
  },
  titleAccent: {
    background: `linear-gradient(90deg, ${colors.accent.yellow} 0%, rgba(255,255,255,0.95) 60%)`,
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
  },
  subtitle: {
    margin: '12px auto 0',
    maxWidth: 720,
    fontSize: 16,
    fontWeight: 750,
    color: 'rgba(255,255,255,0.92)',
    lineHeight: 1.6,
    textShadow: '0 10px 26px rgba(0,0,0,0.14)',
  },

  card: {
    marginTop: 16,
    background: colors.neutral.white,
    borderRadius: 22,
    padding: 18,
    boxShadow: '0 22px 60px rgba(0,0,0,0.18)',
  },

  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(360px, 1fr))',
    gap: 16,
  },
  gridMt14: {
    marginTop: 14,
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(360px, 1fr))',
    gap: 16,
  },

  section: {
    borderRadius: 18,
    border: `1px solid ${colors.neutral[200]}`,
    background: colors.neutral[50],
    padding: 14,
  },
  sectionTitle: {
    margin: 0,
    fontSize: 16,
    fontWeight: 950,
    color: colors.neutral[900],
    letterSpacing: -0.3,
  },
  sectionSub: {
    marginTop: 6,
    fontSize: 13,
    fontWeight: 750,
    color: colors.neutral[700],
    lineHeight: 1.5,
  },

  row: {
    marginTop: 12,
    display: 'flex',
    gap: 10,
    flexWrap: 'wrap',
    alignItems: 'center',
  },
  input: {
    height: 46,
    padding: '0 14px',
    borderRadius: 14,
    border: `1px solid ${colors.neutral[200]}`,
    background: colors.neutral.white,
    fontSize: 14,
    fontWeight: 750,
    color: colors.neutral[900],
    outline: 'none',
    boxShadow: '0 10px 24px rgba(0,0,0,0.06)',
    flex: '1 1 240px',
  },
  btn: {
    height: 46,
    padding: '0 16px',
    borderRadius: 16,
    border: `1px solid ${colors.neutral[200]}`,
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 950,
    boxShadow: '0 12px 26px rgba(0,0,0,0.10)',
  },
  btnWhite: {
    height: 46,
    padding: '0 16px',
    borderRadius: 16,
    border: `1px solid ${colors.neutral[200]}`,
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 950,
    boxShadow: '0 12px 26px rgba(0,0,0,0.10)',
    background: colors.neutral.white,
    color: colors.neutral[900],
  },
  btnPrimary: {
    height: 46,
    padding: '0 16px',
    borderRadius: 16,
    border: 'none',
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 950,
    boxShadow: '0 12px 26px rgba(0,0,0,0.10)',
    background: colors.gradients.main,
    color: colors.neutral.white,
  },
  error: {
    marginTop: 12,
    padding: '10px 12px',
    borderRadius: 16,
    border: `1px solid ${colors.secondary[100]}`,
    background: colors.secondary[50],
    color: colors.secondary[700],
    fontSize: 13,
    fontWeight: 850,
  },
  hint: {
    marginTop: 10,
    fontSize: 12,
    fontWeight: 850,
    color: colors.neutral[700],
  },

  list: {
    marginTop: 12,
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
  },
  listItem: {
    width: '100%',
    textAlign: 'left',
    padding: 12,
    borderRadius: 16,
    border: `1px solid ${colors.neutral[200]}`,
    background: colors.neutral.white,
    cursor: 'pointer',
    boxShadow: '0 12px 26px rgba(0,0,0,0.06)',
  },
  itemTop: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  itemName: {
    fontSize: 14,
    fontWeight: 950,
    color: colors.neutral[900],
  },
  actions: { display: 'flex', gap: 8, flexWrap: 'wrap' },
  miniBtn: {
    height: 32,
    padding: '0 10px',
    borderRadius: 999,
    border: `1px solid ${colors.neutral[200]}`,
    cursor: 'pointer',
    fontSize: 12,
    fontWeight: 950,
    background: colors.neutral.white,
  },
  miniBtnPrimary: {
    height: 32,
    padding: '0 10px',
    borderRadius: 999,
    border: 'none',
    cursor: 'pointer',
    fontSize: 12,
    fontWeight: 950,
    background: colors.gradients.main,
    color: colors.neutral.white,
  },
  sideCol: { display: 'flex', flexDirection: 'column', gap: 16 },

  statsBox: {
    marginTop: 12,
    borderRadius: 16,
    border: `1px solid ${colors.neutral[200]}`,
    background: colors.neutral.white,
    padding: 12,
  },
  statsRow: {
    display: 'flex',
    gap: 10,
    flexWrap: 'wrap',
    alignItems: 'center',
  },
  statPill: {
    padding: '7px 10px',
    borderRadius: 999,
    background: colors.neutral[50],
    border: `1px solid ${colors.neutral[200]}`,
    fontSize: 12,
    fontWeight: 950,
    color: colors.neutral[800],
  },
  subTitle: {
    marginTop: 12,
    fontSize: 13,
    fontWeight: 950,
    color: colors.neutral[900],
  },
  small: {
    marginTop: 6,
    fontSize: 12,
    fontWeight: 800,
    color: colors.neutral[700],
  },

  lockCard: {
    background: colors.neutral.white,
    borderRadius: 22,
    padding: 22,
    boxShadow: '0 22px 60px rgba(0,0,0,0.18)',
    textAlign: 'center',
    maxWidth: 520,
    margin: '0 auto',
  },
  lockTitle: {
    margin: 0,
    fontSize: 22,
    fontWeight: 950,
    color: colors.neutral[900],
    letterSpacing: -0.5,
  },
  lockText: {
    marginTop: 10,
    fontSize: 14,
    fontWeight: 750,
    color: colors.neutral[700],
    lineHeight: 1.6,
  },
  primaryBtn: {
    marginTop: 14,
    width: '100%',
    height: 46,
    borderRadius: 16,
    border: 'none',
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 950,
    color: colors.neutral.white,
    boxShadow: '0 14px 30px rgba(0,0,0,0.16)',
  },
  primaryBtnMain: {
    marginTop: 14,
    width: '100%',
    height: 46,
    borderRadius: 16,
    border: 'none',
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 950,
    color: colors.neutral.white,
    boxShadow: '0 14px 30px rgba(0,0,0,0.16)',
    background: colors.gradients.main,
  },
  secondaryBtn: {
    marginTop: 10,
    width: '100%',
    height: 46,
    borderRadius: 16,
    border: `1px solid ${colors.neutral[200]}`,
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 950,
    boxShadow: '0 14px 30px rgba(0,0,0,0.10)',
  },
  secondaryBtnWhite: {
    marginTop: 10,
    width: '100%',
    height: 46,
    borderRadius: 16,
    border: `1px solid ${colors.neutral[200]}`,
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 950,
    boxShadow: '0 14px 30px rgba(0,0,0,0.10)',
    background: colors.neutral.white,
    color: colors.neutral[900],
  },
};

export default FriendsStyle;
