import colors from '../../constants/colors';

const FriendProfileStyle = {
  page: {
    width: '100%',
    background: colors.gradients.main,
    display: 'flex',
    justifyContent: 'center',
    padding: '36px 18px 74px',
  },
  container: {
    width: '100%',
    maxWidth: 1180,
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
  },

  topRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
    flexWrap: 'wrap',
  },
  topActions: { display: 'flex', gap: 10, flexWrap: 'wrap' },
  btn: {
    height: 46,
    padding: '0 16px',
    borderRadius: 16,
    border: `1px solid ${colors.neutral[200]}`,
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 950,
    boxShadow: '0 12px 26px rgba(0,0,0,0.10)',
  },
  btnWhite: {
    height: 46,
    padding: '0 16px',
    borderRadius: 16,
    border: `1px solid ${colors.neutral[200]}`,
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 950,
    boxShadow: '0 12px 26px rgba(0,0,0,0.10)',
    background: colors.neutral.white,
    color: colors.neutral[900],
  },
  btnPrimary: {
    height: 46,
    padding: '0 16px',
    borderRadius: 16,
    border: 'none',
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 950,
    boxShadow: '0 12px 26px rgba(0,0,0,0.10)',
    background: colors.gradients.main,
    color: colors.neutral.white,
  },

  headerCard: {
    background: colors.neutral.white,
    borderRadius: 26,
    padding: 22,
    boxShadow: '0 22px 60px rgba(0,0,0,0.18)',
  },
  headerTop: {
    display: 'flex',
    alignItems: 'center',
    gap: 14,
    flexWrap: 'wrap',
  },
  nameWrap: { flex: 1, minWidth: 220 },
  handshakeIcon: { fontSize: 18 },
  avatar: {
    width: 56,
    height: 56,
    borderRadius: 18,
    background: colors.gradients.main,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: colors.neutral.white,
    fontSize: 22,
    fontWeight: 950,
    boxShadow: '0 14px 30px rgba(0,0,0,0.14)',
    overflow: 'hidden',
  },
  avatarImg: { width: '100%', height: '100%', objectFit: 'cover' },
  name: {
    margin: 0,
    fontSize: 24,
    fontWeight: 950,
    color: colors.neutral[900],
    letterSpacing: -0.4,
    lineHeight: 1.1,
  },
  sub: {
    marginTop: 6,
    fontSize: 13,
    fontWeight: 850,
    color: colors.neutral[700],
  },

  pills: {
    marginTop: 14,
    display: 'flex',
    gap: 10,
    flexWrap: 'wrap',
    alignItems: 'center',
  },
  pill: {
    padding: '8px 12px',
    borderRadius: 999,
    background: colors.neutral[50],
    border: `1px solid ${colors.neutral[200]}`,
    fontSize: 12,
    fontWeight: 950,
    color: colors.neutral[800],
  },

  sectionCard: {
    background: colors.neutral.white,
    borderRadius: 26,
    padding: 18,
    boxShadow: '0 22px 60px rgba(0,0,0,0.18)',
  },
  sectionTitle: {
    margin: 0,
    fontSize: 16,
    fontWeight: 950,
    color: colors.neutral[900],
    letterSpacing: -0.3,
  },
  sectionSub: {
    marginTop: 6,
    fontSize: 13,
    fontWeight: 750,
    color: colors.neutral[700],
    lineHeight: 1.5,
  },

  list: {
    marginTop: 14,
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
  },
  item: {
    width: '100%',
    textAlign: 'left',
    padding: 14,
    borderRadius: 18,
    border: `1px solid ${colors.neutral[200]}`,
    background: colors.neutral.white,
    cursor: 'pointer',
    boxShadow: '0 12px 26px rgba(0,0,0,0.06)',
  },
  itemTop: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  itemTitle: {
    fontSize: 14,
    fontWeight: 950,
    color: colors.neutral[900],
    letterSpacing: -0.2,
  },
  scorePill: {
    padding: '7px 10px',
    borderRadius: 999,
    background: colors.neutral[50],
    border: `1px solid ${colors.neutral[200]}`,
    fontSize: 12,
    fontWeight: 950,
    color: colors.neutral[800],
    whiteSpace: 'nowrap',
  },
  meta: {
    marginTop: 8,
    fontSize: 12,
    fontWeight: 850,
    color: colors.neutral[700],
  },

  errorCard: {
    background: colors.neutral.white,
    borderRadius: 22,
    padding: 16,
    border: `1px solid ${colors.secondary[100]}`,
    color: colors.secondary[700],
    fontSize: 13,
    fontWeight: 850,
    boxShadow: '0 18px 50px rgba(0,0,0,0.16)',
  },

  lockCard: {
    background: colors.neutral.white,
    borderRadius: 22,
    padding: 22,
    boxShadow: '0 22px 60px rgba(0,0,0,0.18)',
    textAlign: 'center',
    maxWidth: 520,
    margin: '0 auto',
  },
  lockTitle: {
    margin: 0,
    fontSize: 22,
    fontWeight: 950,
    color: colors.neutral[900],
    letterSpacing: -0.5,
  },
  lockText: {
    marginTop: 10,
    fontSize: 14,
    fontWeight: 750,
    color: colors.neutral[700],
    lineHeight: 1.6,
  },
  primaryBtn: {
    marginTop: 14,
    width: '100%',
    height: 46,
    borderRadius: 16,
    border: 'none',
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 950,
    color: colors.neutral.white,
    boxShadow: '0 14px 30px rgba(0,0,0,0.16)',
  },
  primaryBtnMain: {
    marginTop: 14,
    width: '100%',
    height: 46,
    borderRadius: 16,
    border: 'none',
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 950,
    color: colors.neutral.white,
    boxShadow: '0 14px 30px rgba(0,0,0,0.16)',
    background: colors.gradients.main,
  },
  secondaryBtn: {
    marginTop: 10,
    width: '100%',
    height: 46,
    borderRadius: 16,
    border: `1px solid ${colors.neutral[200]}`,
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 950,
    boxShadow: '0 14px 30px rgba(0,0,0,0.10)',
  },
  secondaryBtnWhite: {
    marginTop: 10,
    width: '100%',
    height: 46,
    borderRadius: 16,
    border: `1px solid ${colors.neutral[200]}`,
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 950,
    boxShadow: '0 14px 30px rgba(0,0,0,0.10)',
    background: colors.neutral.white,
    color: colors.neutral[900],
  },
};

export default FriendProfileStyle;
