import colors from '../../constants/colors';

const LeaderboardStyle = {
  page: {
    width: '100%',
    background: colors.gradients.main,
    display: 'flex',
    justifyContent: 'center',
    padding: '52px 18px 74px',
    minHeight: 'calc(100vh - 72px)',
  },
  container: {
    width: '100%',
    maxWidth: 1180,
  },
  hero: {
    textAlign: 'center',
    marginBottom: 18,
  },
  badge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 10,
    padding: '10px 16px',
    borderRadius: 999,
    background: 'rgba(255,255,255,0.92)',
    boxShadow: '0 14px 30px rgba(0,0,0,0.14)',
    marginBottom: 18,
  },
  badgeIcon: { fontSize: 16 },
  badgeText: {
    fontSize: 13,
    fontWeight: 900,
    color: colors.primary[600],
  },
  badgeDot: { fontSize: 16 },
  title: {
    margin: 0,
    fontSize: 56,
    fontWeight: 950,
    letterSpacing: -0.9,
    color: colors.neutral.white,
    textShadow: '0 14px 40px rgba(0,0,0,0.18)',
  },
  subtitle: {
    margin: '12px auto 0',
    maxWidth: 760,
    fontSize: 16,
    fontWeight: 750,
    color: 'rgba(255,255,255,0.92)',
    lineHeight: 1.6,
    textShadow: '0 10px 26px rgba(0,0,0,0.14)',
  },
  card: {
    marginTop: 16,
    background: colors.neutral.white,
    borderRadius: 22,
    padding: 18,
    boxShadow: '0 22px 60px rgba(0,0,0,0.18)',
  },
  row: {
    display: 'flex',
    gap: 10,
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  btn: {
    height: 46,
    padding: '0 16px',
    borderRadius: 16,
    border: `1px solid ${colors.neutral[200]}`,
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 950,
    boxShadow: '0 12px 26px rgba(0,0,0,0.10)',
    background: colors.neutral.white,
    color: colors.neutral[900],
  },
  select: {
    height: 44,
    padding: '0 12px',
    borderRadius: 14,
    border: `1px solid ${colors.neutral[200]}`,
    outline: 'none',
    fontSize: 14,
    fontWeight: 900,
    color: colors.neutral[900],
    background: colors.neutral.white,
    boxShadow: '0 10px 24px rgba(0,0,0,0.08)',
  },
  error: {
    marginTop: 12,
    padding: '10px 12px',
    borderRadius: 16,
    border: `1px solid ${colors.secondary[100]}`,
    background: colors.secondary[50],
    color: colors.secondary[700],
    fontSize: 13,
    fontWeight: 850,
  },
  list: {
    marginTop: 14,
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
  },
  item: {
    padding: 12,
    borderRadius: 18,
    border: `1px solid ${colors.neutral[200]}`,
    background: colors.neutral[50],
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  left: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    minWidth: 0,
  },
  rank: {
    width: 44,
    height: 44,
    borderRadius: 14,
    background: colors.neutral.white,
    border: `1px solid ${colors.neutral[200]}`,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: 950,
    color: colors.primary[700],
  },
  name: {
    fontSize: 14,
    fontWeight: 950,
    color: colors.neutral[900],
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    maxWidth: 360,
  },
  meta: {
    marginTop: 2,
    fontSize: 12,
    fontWeight: 850,
    color: colors.neutral[650],
  },
  score: {
    padding: '10px 12px',
    borderRadius: 999,
    background: colors.neutral.white,
    border: `1px solid ${colors.neutral[200]}`,
    fontSize: 13,
    fontWeight: 950,
    color: colors.neutral[900],
    whiteSpace: 'nowrap',
  },
};

export default LeaderboardStyle;

