import colors from '../../constants/colors';

const MyPlaysStyle = {
  page: {
    width: '100%',
    background: colors.gradients.main,
    display: 'flex',
    justifyContent: 'center',
    padding: '52px 18px 74px',
  },
  container: {
    width: '100%',
    maxWidth: 1180,
  },

  hero: {
    textAlign: 'center',
    marginBottom: 18,
  },
  badge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 10,
    padding: '10px 16px',
    borderRadius: 999,
    background: 'rgba(255,255,255,0.92)',
    boxShadow: '0 14px 30px rgba(0,0,0,0.14)',
    marginBottom: 18,
  },
  badgeIcon: { fontSize: 16 },
  badgeText: {
    fontSize: 13,
    fontWeight: 900,
    color: colors.primary[600],
  },
  badgeDot: { fontSize: 16 },

  title: {
    margin: 0,
    fontSize: 56,
    fontWeight: 950,
    letterSpacing: -0.9,
    color: colors.neutral.white,
    textShadow: '0 14px 40px rgba(0,0,0,0.18)',
  },
  titleAccent: {
    background: `linear-gradient(90deg, ${colors.accent.yellow} 0%, rgba(255,255,255,0.95) 60%)`,
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
  },
  subtitle: {
    margin: '12px auto 0',
    maxWidth: 720,
    fontSize: 16,
    fontWeight: 750,
    color: 'rgba(255,255,255,0.92)',
    lineHeight: 1.6,
    textShadow: '0 10px 26px rgba(0,0,0,0.14)',
  },

  card: {
    marginTop: 16,
    background: colors.neutral.white,
    borderRadius: 22,
    padding: 18,
    boxShadow: '0 22px 60px rgba(0,0,0,0.18)',
  },
  topRow: {
    display: 'flex',
    gap: 10,
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  input: {
    height: 46,
    padding: '0 14px',
    borderRadius: 14,
    border: `1px solid ${colors.neutral[200]}`,
    background: colors.neutral.white,
    fontSize: 14,
    fontWeight: 700,
    color: colors.neutral[900],
    outline: 'none',
    boxShadow: '0 10px 24px rgba(0,0,0,0.06)',
    flex: '1 1 320px',
  },
  btn: {
    height: 46,
    padding: '0 16px',
    borderRadius: 16,
    border: `1px solid ${colors.neutral[200]}`,
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 950,
    boxShadow: '0 12px 26px rgba(0,0,0,0.10)',
  },
  btnWhite: {
    height: 46,
    padding: '0 16px',
    borderRadius: 16,
    border: `1px solid ${colors.neutral[200]}`,
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 950,
    boxShadow: '0 12px 26px rgba(0,0,0,0.10)',
    background: colors.neutral.white,
    color: colors.neutral[900],
  },
  btnPrimary: {
    height: 46,
    padding: '0 16px',
    borderRadius: 16,
    border: `1px solid ${colors.neutral[200]}`,
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 950,
    boxShadow: '0 12px 26px rgba(0,0,0,0.10)',
    background: colors.gradients.main,
    color: colors.neutral.white,
  },
  error: {
    marginTop: 12,
    padding: '10px 12px',
    borderRadius: 16,
    border: `1px solid ${colors.secondary[100]}`,
    background: colors.secondary[50],
    color: colors.secondary[700],
    fontSize: 13,
    fontWeight: 850,
  },

  list: {
    marginTop: 14,
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
    maxHeight: 520,
    overflow: 'auto',
    paddingRight: 6,
  },
  item: {
    width: '100%',
    textAlign: 'left',
    padding: 16,
    borderRadius: 22,
    border: `1px solid ${colors.neutral[200]}`,
    background: colors.neutral.white,
    cursor: 'pointer',
    boxShadow: '0 18px 50px rgba(0,0,0,0.12)',
  },
  itemTop: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
    flexWrap: 'wrap',
  },
  itemTitle: {
    fontSize: 18,
    fontWeight: 950,
    color: colors.neutral[900],
    letterSpacing: -0.4,
  },
  scorePill: {
    padding: '7px 10px',
    borderRadius: 999,
    background: colors.neutral[100],
    border: `1px solid ${colors.neutral[200]}`,
    color: colors.neutral[900],
    fontSize: 12,
    fontWeight: 950,
    whiteSpace: 'nowrap',
  },
  meta: {
    marginTop: 10,
    display: 'flex',
    gap: 10,
    flexWrap: 'wrap',
    alignItems: 'center',
  },
  metaItem: {
    padding: '7px 10px',
    borderRadius: 999,
    background: colors.neutral[50],
    border: `1px solid ${colors.neutral[200]}`,
    color: colors.neutral[800],
    fontSize: 12,
    fontWeight: 900,
  },

  empty: {
    marginTop: 6,
    padding: '12px 12px',
    borderRadius: 16,
    background: colors.neutral[50],
    border: `1px solid ${colors.neutral[200]}`,
    color: colors.neutral[700],
    fontSize: 13,
    fontWeight: 850,
  },

  lockCard: {
    maxWidth: 560,
    margin: '18px auto 0',
    borderRadius: 22,
    padding: 26,
    background: colors.neutral.white,
    boxShadow: '0 22px 60px rgba(0,0,0,0.18)',
    textAlign: 'center',
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
  },
  lockTitle: {
    margin: 0,
    fontSize: 24,
    fontWeight: 950,
    color: colors.neutral[900],
    letterSpacing: -0.5,
  },
  lockText: {
    margin: 0,
    fontSize: 14,
    fontWeight: 750,
    color: colors.neutral[600],
    lineHeight: 1.55,
  },
  primaryBtn: {
    height: 48,
    borderRadius: 16,
    border: 'none',
    cursor: 'pointer',
    color: colors.neutral.white,
    fontSize: 15,
    fontWeight: 950,
    boxShadow: '0 18px 34px rgba(139,44,255,0.28)',
  },
  primaryBtnMain: {
    height: 48,
    borderRadius: 16,
    border: 'none',
    cursor: 'pointer',
    color: colors.neutral.white,
    fontSize: 15,
    fontWeight: 950,
    boxShadow: '0 18px 34px rgba(139,44,255,0.28)',
    background: colors.gradients.main,
  },
  secondaryBtn: {
    height: 46,
    padding: '0 16px',
    borderRadius: 16,
    border: `1px solid ${colors.neutral[200]}`,
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 950,
    color: colors.neutral[900],
    boxShadow: '0 12px 26px rgba(0,0,0,0.10)',
  },
  secondaryBtnWhite: {
    height: 46,
    padding: '0 16px',
    borderRadius: 16,
    border: `1px solid ${colors.neutral[200]}`,
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 950,
    color: colors.neutral[900],
    boxShadow: '0 12px 26px rgba(0,0,0,0.10)',
    background: colors.neutral.white,
  },
};

export default MyPlaysStyle;
