import colors from '../../constants/colors';

const PlaySessionStyle = {
  page: {
    width: '100%',
    background: colors.gradients.main,
    display: 'flex',
    justifyContent: 'center',
    padding: '36px 18px 74px',
  },
  container: {
    width: '100%',
    maxWidth: 980,
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
  },

  topRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    flexWrap: 'wrap',
  },
  pills: {
    display: 'flex',
    gap: 8,
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  pill: {
    padding: '8px 12px',
    borderRadius: 999,
    background: 'rgba(255,255,255,0.18)',
    border: '1px solid rgba(255,255,255,0.22)',
    color: colors.neutral.white,
    fontSize: 12,
    fontWeight: 950,
    boxShadow: 'inset 0 1px 0 rgba(255,255,255,0.18)',
    backdropFilter: 'blur(10px)',
  },

  card: {
    background: colors.neutral.white,
    borderRadius: 26,
    padding: 20,
    boxShadow: '0 22px 60px rgba(0,0,0,0.18)',
  },
  qText: {
    fontSize: 18,
    fontWeight: 950,
    color: colors.neutral[900],
    letterSpacing: -0.4,
    lineHeight: 1.35,
  },
  options: {
    marginTop: 16,
    display: 'grid',
    gridTemplateColumns: 'repeat(1, minmax(0, 1fr))',
    gap: 12,
  },
  optionBtn: {
    width: '100%',
    textAlign: 'left',
    padding: 14,
    borderRadius: 20,
    border: `1px solid ${colors.neutral[200]}`,
    background: colors.neutral.white,
    cursor: 'pointer',
    boxShadow: '0 14px 30px rgba(0,0,0,0.10)',
    display: 'flex',
    gap: 12,
    alignItems: 'center',
  },
  optionBtnActive: {
    border: `1px solid ${colors.primary[200]}`,
    background: colors.primary[50],
  },
  optionLabel: {
    width: 34,
    height: 34,
    borderRadius: 14,
    background: colors.neutral[100],
    border: `1px solid ${colors.neutral[200]}`,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 12,
    fontWeight: 950,
    color: colors.neutral[800],
    flex: '0 0 auto',
  },
  optionText: {
    fontSize: 14,
    fontWeight: 850,
    color: colors.neutral[900],
    lineHeight: 1.35,
  },

  actions: {
    marginTop: 16,
    display: 'flex',
    gap: 10,
    flexWrap: 'wrap',
  },
  primaryBtn: {
    height: 46,
    padding: '0 18px',
    borderRadius: 16,
    border: 'none',
    cursor: 'pointer',
    color: colors.neutral.white,
    fontSize: 14,
    fontWeight: 950,
    boxShadow: '0 18px 34px rgba(139,44,255,0.28)',
  },
  secondaryBtn: {
    height: 46,
    padding: '0 16px',
    borderRadius: 16,
    border: `1px solid ${colors.neutral[200]}`,
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 950,
    color: colors.neutral[900],
    boxShadow: '0 12px 26px rgba(0,0,0,0.10)',
  },

  result: {
    marginTop: 14,
    padding: '10px 12px',
    borderRadius: 16,
    fontSize: 13,
    fontWeight: 950,
  },
  resultOk: {
    background: 'rgba(34,197,94,0.12)',
    border: '1px solid rgba(34,197,94,0.35)',
    color: colors.accent.green,
  },
  resultBad: {
    background: 'rgba(239,68,68,0.12)',
    border: '1px solid rgba(239,68,68,0.35)',
    color: colors.accent.red,
  },
  bonus: {
    marginLeft: 10,
    padding: '4px 8px',
    borderRadius: 999,
    background: 'rgba(255,204,0,0.16)',
    border: '1px solid rgba(255,204,0,0.38)',
    color: colors.neutral[900],
    fontSize: 12,
    fontWeight: 950,
  },

  errorCard: {
    background: colors.neutral.white,
    borderRadius: 22,
    padding: 16,
    border: `1px solid ${colors.secondary[100]}`,
    color: colors.secondary[700],
    fontSize: 13,
    fontWeight: 850,
    boxShadow: '0 18px 50px rgba(0,0,0,0.16)',
  },
  loading: {
    textAlign: 'center',
    color: colors.neutral.white,
    fontSize: 14,
    fontWeight: 850,
    textShadow: '0 10px 26px rgba(0,0,0,0.16)',
    padding: '22px 0',
  },

  lockCard: {
    maxWidth: 560,
    margin: '18px auto 0',
    borderRadius: 22,
    padding: 26,
    background: colors.neutral.white,
    boxShadow: '0 22px 60px rgba(0,0,0,0.18)',
    textAlign: 'center',
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
  },
  lockTitle: {
    margin: 0,
    fontSize: 24,
    fontWeight: 950,
    color: colors.neutral[900],
    letterSpacing: -0.5,
  },
  lockText: {
    margin: 0,
    fontSize: 14,
    fontWeight: 750,
    color: colors.neutral[600],
    lineHeight: 1.55,
  },

  doneCard: {
    background: colors.neutral.white,
    borderRadius: 26,
    padding: 22,
    boxShadow: '0 22px 60px rgba(0,0,0,0.18)',
    textAlign: 'center',
  },
  doneTitle: {
    margin: 0,
    fontSize: 26,
    fontWeight: 950,
    color: colors.neutral[900],
    letterSpacing: -0.6,
  },
  doneText: {
    margin: '10px 0 18px',
    fontSize: 14,
    fontWeight: 850,
    color: colors.neutral[700],
  },
};

export default PlaySessionStyle;
