import colors from '../../constants/colors';

const ProfileStyle = {
  page: {
    width: '100%',
    background: colors.gradients.main,
    display: 'flex',
    justifyContent: 'center',
    padding: '52px 18px 74px',
  },
  container: {
    width: '100%',
    maxWidth: 1180,
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
  },

  lockCard: {
    width: '100%',
    maxWidth: 520,
    margin: '0 auto',
    background: 'rgba(255,255,255,0.92)',
    borderRadius: 22,
    padding: 20,
    boxShadow: '0 22px 60px rgba(0,0,0,0.18)',
    textAlign: 'center',
  },
  lockTitle: {
    margin: 0,
    fontSize: 22,
    fontWeight: 950,
    color: colors.neutral[900],
    letterSpacing: -0.4,
  },
  lockText: {
    margin: '10px auto 0',
    maxWidth: 420,
    fontSize: 14,
    fontWeight: 750,
    color: colors.neutral[700],
    lineHeight: 1.6,
  },

  topRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    flexWrap: 'wrap',
  },
  topActions: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    flexWrap: 'wrap',
  },

  headerCard: {
    background: colors.neutral.white,
    borderRadius: 26,
    padding: 18,
    boxShadow: '0 22px 60px rgba(0,0,0,0.18)',
  },
  headerTop: {
    display: 'flex',
    alignItems: 'center',
    gap: 14,
    flexWrap: 'wrap',
  },
  avatar: {
    width: 60,
    height: 60,
    borderRadius: 18,
    background: colors.primary[600],
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: colors.neutral.white,
    fontSize: 20,
    fontWeight: 950,
    overflow: 'hidden',
    boxShadow: '0 18px 40px rgba(139,44,255,0.24)',
  },
  avatarImg: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    display: 'block',
  },
  nameWrap: { minWidth: 220 },
  name: {
    margin: 0,
    fontSize: 26,
    fontWeight: 950,
    color: colors.neutral[900],
    letterSpacing: -0.6,
  },
  sub: {
    marginTop: 4,
    fontSize: 13,
    fontWeight: 850,
    color: colors.neutral[600],
  },

  pills: {
    marginTop: 14,
    display: 'flex',
    flexWrap: 'wrap',
    gap: 8,
  },
  pill: {
    padding: '8px 12px',
    borderRadius: 999,
    background: colors.neutral[100],
    border: `1px solid ${colors.neutral[200]}`,
    color: colors.neutral[800],
    fontSize: 12,
    fontWeight: 950,
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
  },

  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))',
    gap: 12,
  },
  modeCard: {
    background: colors.neutral.white,
    borderRadius: 22,
    padding: 16,
    boxShadow: '0 18px 50px rgba(0,0,0,0.16)',
  },
  modeTop: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  modeTitle: {
    margin: 0,
    fontSize: 16,
    fontWeight: 950,
    color: colors.neutral[900],
    letterSpacing: -0.3,
    display: 'flex',
    alignItems: 'center',
    gap: 10,
  },
  modeIcon: {
    width: 34,
    height: 34,
    borderRadius: 14,
    background: colors.neutral[100],
    border: `1px solid ${colors.neutral[200]}`,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 16,
  },
  modeMeta: {
    marginTop: 10,
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: 8,
  },
  stat: {
    padding: '10px 12px',
    borderRadius: 18,
    background: colors.neutral[50],
    border: `1px solid ${colors.neutral[200]}`,
  },
  statLabel: {
    fontSize: 11,
    fontWeight: 900,
    color: colors.neutral[600],
  },
  statValue: {
    marginTop: 4,
    fontSize: 14,
    fontWeight: 950,
    color: colors.neutral[900],
  },

  sectionCard: {
    background: colors.neutral.white,
    borderRadius: 22,
    padding: 18,
    boxShadow: '0 22px 60px rgba(0,0,0,0.18)',
  },
  sectionTitle: {
    margin: 0,
    fontSize: 18,
    fontWeight: 950,
    color: colors.neutral[900],
    letterSpacing: -0.3,
  },
  sectionSub: {
    marginTop: 6,
    fontSize: 13,
    fontWeight: 800,
    color: colors.neutral[600],
  },
  list: {
    marginTop: 14,
    display: 'grid',
    gap: 10,
  },
  item: {
    width: '100%',
    textAlign: 'left',
    padding: 14,
    borderRadius: 18,
    border: `1px solid ${colors.neutral[200]}`,
    background: colors.neutral.white,
    boxShadow: '0 14px 30px rgba(0,0,0,0.10)',
    cursor: 'pointer',
  },
  itemTop: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  itemTitle: {
    fontSize: 14,
    fontWeight: 950,
    color: colors.neutral[900],
  },
  scorePill: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    padding: '6px 10px',
    borderRadius: 999,
    background: colors.primary[50],
    border: `1px solid ${colors.primary[100]}`,
    color: colors.primary[700],
    fontSize: 12,
    fontWeight: 950,
  },
  meta: {
    marginTop: 8,
    fontSize: 12,
    fontWeight: 800,
    color: colors.neutral[600],
  },

  sectionTopRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    flexWrap: 'wrap',
  },

  input: {
    height: 44,
    padding: '0 14px',
    borderRadius: 14,
    border: `1px solid ${colors.neutral[200]}`,
    background: colors.neutral.white,
    fontSize: 14,
    fontWeight: 750,
    color: colors.neutral[900],
    outline: 'none',
    boxShadow: '0 10px 24px rgba(0,0,0,0.06)',
    flex: '1 1 280px',
  },

  itemStatic: {
    width: '100%',
    textAlign: 'left',
    padding: 14,
    borderRadius: 18,
    border: `1px solid ${colors.neutral[200]}`,
    background: colors.neutral.white,
    boxShadow: '0 14px 30px rgba(0,0,0,0.10)',
  },
  row: {
    marginTop: 10,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    flexWrap: 'wrap',
  },
  miniActions: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  miniBtn: {
    height: 38,
    padding: '0 12px',
    borderRadius: 14,
    border: `1px solid ${colors.neutral[200]}`,
    background: colors.neutral.white,
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: 950,
    color: colors.neutral[900],
    boxShadow: '0 10px 22px rgba(0,0,0,0.08)',
    whiteSpace: 'nowrap',
  },
  miniBtnPrimary: {
    height: 38,
    padding: '0 12px',
    borderRadius: 14,
    border: 'none',
    background: colors.gradients.main,
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: 950,
    color: colors.neutral.white,
    boxShadow: '0 14px 26px rgba(139,44,255,0.24)',
    whiteSpace: 'nowrap',
  },
  miniBtnDanger: {
    height: 38,
    padding: '0 12px',
    borderRadius: 14,
    border: `1px solid ${colors.secondary[100]}`,
    background: colors.secondary[50],
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: 950,
    color: colors.secondary[700],
    boxShadow: '0 12px 26px rgba(0,0,0,0.08)',
    whiteSpace: 'nowrap',
  },

  statusPill: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    padding: '6px 10px',
    borderRadius: 999,
    background: colors.neutral[100],
    border: `1px solid ${colors.neutral[200]}`,
    color: colors.neutral[800],
    fontSize: 12,
    fontWeight: 950,
    whiteSpace: 'nowrap',
  },
  statusPillGood: {
    background: colors.primary[50],
    border: `1px solid ${colors.primary[100]}`,
    color: colors.primary[700],
  },
  statusPillBad: {
    background: colors.secondary[50],
    border: `1px solid ${colors.secondary[100]}`,
    color: colors.secondary[700],
  },

  errorCard: {
    background: colors.neutral.white,
    borderRadius: 22,
    padding: 16,
    border: `1px solid ${colors.secondary[100]}`,
    color: colors.secondary[700],
    fontSize: 13,
    fontWeight: 850,
    boxShadow: '0 18px 50px rgba(0,0,0,0.16)',
  },

  btnWhite: {
    height: 46,
    padding: '0 16px',
    borderRadius: 16,
    border: `1px solid ${colors.neutral[200]}`,
    background: colors.neutral.white,
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 950,
    color: colors.neutral[900],
    boxShadow: '0 12px 26px rgba(0,0,0,0.10)',
  },
  btnPrimary: {
    height: 46,
    padding: '0 16px',
    borderRadius: 16,
    border: 'none',
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 950,
    color: colors.neutral.white,
    background: colors.gradients.main,
    boxShadow: '0 18px 34px rgba(139,44,255,0.28)',
  },
  primaryBtnMain: {
    height: 46,
    padding: '0 18px',
    borderRadius: 16,
    border: 'none',
    cursor: 'pointer',
    color: colors.neutral.white,
    fontSize: 14,
    fontWeight: 950,
    boxShadow: '0 18px 34px rgba(139,44,255,0.28)',
    background: colors.gradients.main,
    marginTop: 14,
    width: '100%',
  },
  secondaryBtnWhite: {
    height: 46,
    padding: '0 16px',
    borderRadius: 16,
    border: `1px solid ${colors.neutral[200]}`,
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 950,
    color: colors.neutral[900],
    boxShadow: '0 12px 26px rgba(0,0,0,0.10)',
    background: colors.neutral.white,
    marginTop: 10,
    width: '100%',
  },
};

export default ProfileStyle;
