import colors from '../../constants/colors';

const QuizViewStyle = {
  page: {
    width: '100%',
    background: colors.gradients.main,
    display: 'flex',
    justifyContent: 'center',
    padding: '36px 18px 74px',
  },
  container: {
    width: '100%',
    maxWidth: 1180,
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
  },

  topRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
    flexWrap: 'wrap',
  },
  btn: {
    height: 46,
    padding: '0 16px',
    borderRadius: 16,
    border: `1px solid ${colors.neutral[200]}`,
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 950,
    boxShadow: '0 12px 26px rgba(0,0,0,0.10)',
  },
  btnWhite: {
    height: 46,
    padding: '0 16px',
    borderRadius: 16,
    border: `1px solid ${colors.neutral[200]}`,
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 950,
    boxShadow: '0 12px 26px rgba(0,0,0,0.10)',
    background: colors.neutral.white,
    color: colors.neutral[900],
  },
  btnWhiteMt12: {
    marginTop: 12,
    height: 46,
    padding: '0 16px',
    borderRadius: 16,
    border: `1px solid ${colors.neutral[200]}`,
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 950,
    boxShadow: '0 12px 26px rgba(0,0,0,0.10)',
    background: colors.neutral.white,
    color: colors.neutral[900],
  },
  btnPrimary: {
    height: 46,
    padding: '0 16px',
    borderRadius: 16,
    border: `1px solid ${colors.neutral[200]}`,
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 950,
    boxShadow: '0 12px 26px rgba(0,0,0,0.10)',
    background: colors.gradients.main,
    color: colors.neutral.white,
  },

  errorCard: {
    background: colors.neutral.white,
    borderRadius: 22,
    padding: 16,
    border: `1px solid ${colors.secondary[100]}`,
    color: colors.secondary[700],
    fontSize: 13,
    fontWeight: 850,
    boxShadow: '0 18px 50px rgba(0,0,0,0.16)',
  },

  headerCard: {
    background: colors.neutral.white,
    borderRadius: 26,
    padding: 22,
    boxShadow: '0 22px 60px rgba(0,0,0,0.18)',
  },

  duelCard: {
    background: colors.neutral.white,
    borderRadius: 22,
    padding: 18,
    boxShadow: '0 22px 60px rgba(0,0,0,0.18)',
  },
  duelTop: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
    flexWrap: 'wrap',
  },
  duelTitle: {
    margin: 0,
    fontSize: 18,
    fontWeight: 950,
    color: colors.neutral[900],
    letterSpacing: -0.3,
  },
  duelSub: {
    marginTop: 6,
    fontSize: 13,
    fontWeight: 800,
    color: colors.neutral[600],
  },
  duelRow: {
    marginTop: 14,
    display: 'flex',
    gap: 10,
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  select: {
    height: 46,
    padding: '0 14px',
    borderRadius: 16,
    border: `1px solid ${colors.neutral[200]}`,
    background: colors.neutral.white,
    fontSize: 14,
    fontWeight: 800,
    color: colors.neutral[900],
    outline: 'none',
    boxShadow: '0 12px 26px rgba(0,0,0,0.06)',
    flex: '1 1 280px',
  },
  duelHint: {
    marginTop: 12,
    padding: '10px 12px',
    borderRadius: 16,
    background: colors.neutral[50],
    border: `1px solid ${colors.neutral[200]}`,
    color: colors.neutral[700],
    fontSize: 13,
    fontWeight: 850,
  },
  lbHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    flexWrap: 'wrap',
  },
  lbTitle: {
    margin: 0,
    fontSize: 18,
    fontWeight: 950,
    color: colors.neutral[900],
    letterSpacing: -0.4,
  },
  lbMine: {
    marginTop: 6,
    fontSize: 13,
    fontWeight: 900,
    color: colors.neutral[700],
  },
  lbList: {
    marginTop: 14,
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
  },
  lbRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    padding: '12px 12px',
    borderRadius: 18,
    background: colors.neutral[50],
    border: `1px solid ${colors.neutral[200]}`,
  },
  lbRank: {
    fontSize: 12,
    fontWeight: 950,
    color: colors.neutral[700],
  },
  lbName: {
    flex: 1,
    fontSize: 13,
    fontWeight: 950,
    color: colors.neutral[900],
  },
  lbScore: {
    fontSize: 13,
    fontWeight: 950,
    color: colors.primary[600],
  },
  lbEmpty: {
    padding: '12px 12px',
    borderRadius: 18,
    background: colors.neutral[50],
    border: `1px solid ${colors.neutral[200]}`,
    fontSize: 13,
    fontWeight: 850,
    color: colors.neutral[700],
  },
  headerTop: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 16,
    flexWrap: 'wrap',
  },
  ownerRow: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 10,
    padding: '8px 10px',
    borderRadius: 999,
    background: colors.neutral[100],
    border: `1px solid ${colors.neutral[200]}`,
    color: colors.neutral[800],
    fontSize: 12,
    fontWeight: 900,
    width: 'fit-content',
  },
  ownerIcon: { fontSize: 14 },
  ownerName: { fontWeight: 950 },
  dot: { opacity: 0.7 },
  visibility: { fontWeight: 950 },

  title: {
    margin: '14px 0 0',
    fontSize: 'clamp(24px, 4.6vw, 34px)',
    fontWeight: 950,
    letterSpacing: -0.8,
    color: colors.neutral[900],
  },
  desc: {
    margin: '10px 0 0',
    fontSize: 14,
    fontWeight: 750,
    color: colors.neutral[700],
    lineHeight: 1.55,
    maxWidth: 760,
  },

  ratingBox: {
    padding: 14,
    borderRadius: 22,
    background: colors.neutral[50],
    border: `1px solid ${colors.neutral[200]}`,
    boxShadow: '0 12px 26px rgba(0,0,0,0.06)',
    minWidth: 240,
  },
  ratingText: {
    fontSize: 13,
    fontWeight: 950,
    color: colors.neutral[900],
  },
  starsRow: {
    marginTop: 10,
    display: 'flex',
    gap: 6,
  },
  starBtn: {
    width: 36,
    height: 36,
    borderRadius: 14,
    border: `1px solid ${colors.neutral[200]}`,
    background: colors.neutral.white,
    cursor: 'pointer',
    fontSize: 18,
    fontWeight: 950,
    color: colors.neutral[400],
    boxShadow: '0 10px 22px rgba(0,0,0,0.06)',
  },
  starActive: {
    color: colors.accent.yellow,
    border: `1px solid rgba(255, 204, 0, 0.55)`,
  },
  starBtnState: (active) => ({
    width: 36,
    height: 36,
    borderRadius: 14,
    border: active
      ? '1px solid rgba(255, 204, 0, 0.55)'
      : `1px solid ${colors.neutral[200]}`,
    background: colors.neutral.white,
    cursor: 'pointer',
    fontSize: 18,
    fontWeight: 950,
    color: active ? colors.accent.yellow : colors.neutral[400],
    boxShadow: '0 10px 22px rgba(0,0,0,0.06)',
  }),
  rateHint: {
    marginTop: 10,
    fontSize: 12,
    fontWeight: 850,
    color: colors.neutral[600],
  },

  questions: {
    marginTop: 4,
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(min(360px, 100%), 1fr))',
    gap: 16,
  },
  questionCard: {
    background: colors.neutral.white,
    borderRadius: 22,
    padding: 18,
    boxShadow: '0 18px 50px rgba(0,0,0,0.16)',
    border: `1px solid rgba(255,255,255,0.24)`,
  },
  qTop: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: 12,
    alignItems: 'center',
  },
  qNum: {
    padding: '7px 10px',
    borderRadius: 999,
    background: colors.primary[50],
    border: `1px solid ${colors.primary[100]}`,
    color: colors.primary[700],
    fontSize: 12,
    fontWeight: 950,
  },
  qMeta: {
    fontSize: 12,
    fontWeight: 900,
    color: colors.neutral[700],
  },
  qText: {
    marginTop: 12,
    fontSize: 14,
    fontWeight: 900,
    color: colors.neutral[900],
    lineHeight: 1.45,
  },
  options: {
    marginTop: 12,
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  option: {
    display: 'flex',
    gap: 10,
    alignItems: 'center',
    padding: '10px 12px',
    borderRadius: 16,
    background: colors.neutral[50],
    border: `1px solid ${colors.neutral[200]}`,
  },
  optionIdx: {
    width: 20,
    textAlign: 'right',
    fontSize: 12,
    fontWeight: 950,
    color: colors.neutral[600],
  },
  optionText: {
    fontSize: 13,
    fontWeight: 850,
    color: colors.neutral[900],
  },

  loading: {
    textAlign: 'center',
    color: colors.neutral.white,
    fontSize: 14,
    fontWeight: 850,
    textShadow: '0 10px 26px rgba(0,0,0,0.16)',
    padding: '22px 0',
  },
};

export default QuizViewStyle;
